# Generated by Django 6.0.1 on 2026-01-20 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='priority',
            field=models.IntegerField(choices=[(1, '1 - Very Low'), (2, '2 - Low'), (3, '3 - Medium'), (4, '4 - High'), (5, '5 - Critical')], default=1),
        ),
    ]
